server:
  port: 8088

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

debug: false

rolling:
  start: 2019-01-13 13:00:00
  end: 2019-01-13 14:00:00
  amount: 100
  interval: 600
