debug: false
server:
  port: 8088

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.SQLiteDialect
    generate-ddl: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:application.db
#    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=PRC
#    username: root
#    password: 1234

rolling:
  start: 2019-01-13 13:00:00
  end: 2019-01-13 14:00:00
  amount: 100
  interval: 600
